# Generated by Django 5.1 on 2024-09-09 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchase",
            old_name="menu_item",
            new_name="purchased_item",
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="quantity",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="unit_price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 9, 9, 9, 13, 7, 558908)
            ),
        ),
    ]
