# Generated by Django 5.1 on 2024-09-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reciperequirement",
            name="quantity",
            field=models.FloatField(default=0.0),
        ),
    ]
