# Generated by Django 5.1 on 2024-08-26 00:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reciperequirement",
            old_name="Ingredient",
            new_name="ingredient",
        ),
    ]
