# Generated by Django 5.1 on 2024-09-09 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_rename_menu_item_purchase_purchased_item_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 9, 9, 10, 55, 11, 120375)
            ),
        ),
    ]
